repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [ --unsafe ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
      - id: isort
        args: [ "--filter-files" ]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-typing-imports==1.10.0 ]
  {%- if cookiecutter.use_mypy == 'y' %}
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.901
    hooks:
      - id: mypy
        exclude: tests/
        {% if cookiecutter.command_line_interface|lower == 'click' -%}
        additional_dependencies:
          - types-click
        {%- endif %}
  {%- endif %}
